### ISSUE TITLE
Hardcoded frame name base_footprint in odometryCB function

### ISSUE THREAD

**Issue by AravindaDP** [ipa320/cob_navigation#116]
cob_linear_nav uses hardcoded robot specific tf frame in following locations.

https://github.com/ipa320/cob_navigation/blob/indigo_dev/cob_linear_nav/src/cob_linear_nav.cpp#L284

https://github.com/ipa320/cob_navigation/blob/indigo_dev/cob_linear_nav/src/cob_linear_nav.cpp#L293

This prevents from using this package in a multi robot environment. Following is my current tf tree. There could be multiples of such tree with different tf prefix (scout_1_tf, scout_2_tf etc) All ultimately connected by either static transform between <robot>/odom frames or through a parent map frame (world fixed). (On other hand why we need transforming odom vector to robot relative tf frame? Can't we just use raw value of odom without transforming?)

[frames.pdf](https://github.com/ipa320/cob_navigation/files/5041652/frames.pdf)

Probably I might have setup all these in incorrect way or misunderstanding on how to use this package. But I believe if above two lines used a configurable value through rosparams I could get it to work. (Or `robot_twist_linear_robot_` and `robot_twist_angular_robot_` were simply assigned from `odometry->twist.twist` without any transform)

Thanks for your time

**Comment by floweisshardt** [comment]
the reason for using `TF` instead of raw odometry is that you can specify any frame as `robot_frame` which will allow linear_nav to track those frame.

Your suggestion for using a rosparam instead of hardcoded `base_footprint` is OK. Could you prepare a PR for that?
