### ISSUE TITLE
Fixed velocity thresholds in cob_linear_nav NodeClass::notMovingDueToObstacle()

### ISSUE THREAD

**Issue by AravindaDP** [ipa320/cob_navigation#118]
cob_linear_nav uses hardcoded and tight velocity tolerances in detecting not moving due to obstacle.

https://github.com/ipa320/cob_navigation/blob/indigo_dev/cob_linear_nav/src/cob_linear_nav.cpp#L475

While it may not be intended for using outside cob family of robots, I have been successfully using this package as a generic package on different other robots. However above fixed and tight velocity tolerances causes problems where robot's odometer have inherent noise (e.g. Visual/Inertial only odometer)

I suggest setting above tolerance based on a ros param value (or two in case linear and angular thresholds need to be different) I'm glad to provide a PR if it is a welcome enhancement.

**Comment by fmessmer** [comment]
@AravindaDP 
happy to here that `cob_linear_nav` is being used on other robots, too
sure, if these un-configurable thresholds prevent you from getting better results then it's not a questions that those should be made configurable
please go ahead an provide a pr where these thresholds could be configured from a private namespace as done for many other parameters in https://github.com/ipa320/cob_navigation/blob/indigo_dev/cob_linear_nav/src/cob_linear_nav.cpp#L89-L142
please make sure the default value stays the same - to not change behavior unexpectedly
