### ISSUE TITLE
No cob_unified_scan_publisher in hydro-dev branch

### ISSUE THREAD

**Issue by destogl** [ipa320/cob_navigation#23]
I just want to check again for an old [problem which I have with tf2_ros::TransformListener](http://answers.ros.org/question/80206/why-cant-initialize-tf2_rostransformlistenter-in-hydro/?answer=80261#post-id-80261) but than couldn't find cob_unified_scan_publisher any more in cob_driver/cob_sick_s300 package. So i got confused when wasn't here also, but that's because it only added to groovy-dev, but not hydro-dev branch.

Can you please add it also into hydro-dev branch. Thanks!

**Comment by mgruhler** [comment]
Done, see Pull request #24
