### ISSUE TITLE
cob_scan_unifier is not merging complete scans in simulation

### ISSUE THREAD

**Issue by benmaidel** [ipa320/cob_navigation#53]
scan unifier produce gap on the back of cob4-2
![screenshot from 2015-09-17 14 01 09](https://cloud.githubusercontent.com/assets/483721/9932505/bbfbda80-5d44-11e5-9da1-362de7ea780a.png)

@ipa-frm @ipa-mig

**Comment by mgruhler** [comment]
hmm, also, there is a z-offset (which will probably not be a problem for our use-cases... but we should change that anyways...

**Comment by benmaidel** [comment]
the z-offset seems to be ok. Imagine the scanners are mounted in different z positions (eg. our BMW). So transform the scans to the ground is ok, from my opinion. A better solution would be the usage of a point cloud instead a merged scan message.

**Comment by benmaidel** [comment]
https://github.com/iralabdisco/ira_laser_tools 
there you can find a tool with the same purpose as cob_scan_unifier.
Difference: 
- no gaps
- dynamic reconfigure
- offers point cloud 2 as well

Perhaps we should stick to this package? We could even copy the code from this package to our repo, because it has no license at all.

**Comment by benmaidel** [comment]
This issue was moved to ipa320/cob_driver#249
