### ISSUE TITLE
handle canTransform in cob_linear_nav properly

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_navigation#64]
throws a lot of exceptions and warnings on the terminal

**Comment by fmessmer** [comment]
@ipa-mig @ipa-fmw 
How can I test this?
I run:
`roslaunch cob_bringup_sim robot.launch robot:=cob4-2 robot_env:=ipa-apartment`
`roslaunch cob_navigation_global 2dnav_linear.launch robot:=cob4-2 robot_env:=ipa-apartment`
`roslaunch cob_navigation_global rviz.launch`

What's the easiest way of triggering the action?
When I use
`rosrun actionlib axclient.py /move_base_linear`
and enter a pose wrt `map` (that is reachable), e.g. -0.5 in y direction, nothing moves and I get the response:

```
[ INFO] [1458205353.377222183, 65.162000000]: In idle mode, new goal accepted
[ INFO] [1458205366.456715087, 70.172000000]: Cancel the goal because an obstacle is blocking the path.
[ INFO] [1458205366.456766328, 70.172000000]: Goal not active anymore. Stop!
```

but there are no canTransform exceptions except a single one at startup:

```
[ WARN] [1458205212.669524139]: Used default parameter for use_move_action [true]
[ WARN] [1458205212.803354408, 8.838000000]: Waiting on transform from base_link to map to become available before running cob_linear_nav, tf error: . canTransform returned after 8.838 timeout was 0.1.
```

**Comment by fmessmer** [comment]
for the record:
this issue arose from https://github.com/ipa320/cob_power_management/pull/11

**Comment by floweisshardt** [comment]
This issues popped up again because the TF logs entirely filled up disk space! I could track it down to the waitForTransform in https://github.com/ipa320/cob_navigation/blob/indigo_dev/cob_linear_nav/src/cob_linear_nav.cpp#L194. This is called in a while loop, so as long as there is no transformation between the robot frame and the global frame we'll produce log output with 10Hz which fills up disk space quite fast.

@ipa-mig: do you see a solution to replace the while(waitForTransform) with something else which does not trigger TF error messages that frequently?

**Comment by floweisshardt** [comment]
@ipa-mig, @ipa-srd: any update here?

**Comment by stefandoerr** [comment]
I have fixed this in https://github.com/ipa320/cob_navigation/pull/72
But needs further testing until it can be merged

**Comment by floweisshardt** [comment]
docking still works as expected.

BUT: we're now constantly at 100%CPU load, even without doing something. @ipa-srd: please check and reduce load.

**Comment by mgruhler** [comment]
@ipa-fmw are you using the action interface?

**Comment by floweisshardt** [comment]
yes

**Comment by stefandoerr** [comment]
Tested it in simulation, action interface as well as topic interface. In both cases I had a CPU load of about 6 %.

**Comment by benmaidel** [comment]
@ipa-srd also tested this on his machine in Simulation. No big cpu load

**Comment by floweisshardt** [comment]
tested on robot again: 5-6% CPU load. Although I'm sure I had 100% yesterday, I cannot reproduce this at the moment.

**Comment by stefandoerr** [comment]
I would suggest to wait a few days and observe if this occurs again when testing with robot
