### ISSUE TITLE
[cob_map_accessibility_analysis] format improvements

### ISSUE THREAD

**Issue by mgruhler** [ipa320/cob_navigation#69]
- [x] fix/unify indentation in files
- [x] replace `std::cout` with respective `ROS_DEBUG/INFO/WARN/ERROR`
- [x] replace file headers with new ones, see https://github.com/ipa320/setup/tree/master/templates

**Comment by ipa-rmb** [comment]
Is this done?

**Comment by benmaidel** [comment]
Looks like it is done. I think you can close this.
